databases:
  - name: sqlite3
    ipAllowList: []
    databaseName: db/data.sqlite3
    user: ""

services:
  - type: web
    name: db/data.sqlite3
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sqlite3
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
