services:
  - type: web
    name: rails
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false

#    disk:
#      name: strapi-data
#      mountPath: /data
#      sizeGB: 1

#    envVars:
#      - key: DATABASE_FILENAME
#        value: /data/strapi.db
